---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-conclusion.html 
keywords: conclusion 
summary: 'Ce document fournit des directives de bonnes pratiques pour l"utilisation de Dremio avec le stockage NetApp , y compris les tests de certification TPCDS, le réglage et les détails des cas d"utilisation client.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En conclusion, ce rapport technique a fourni des détails de déploiement complets de q Hybrid Iceberg Lakehouse avec Dremio en conjonction avec diverses sources de données provenant de contrôleurs de stockage NetApp , notamment ONTAP S3, NAS et StorageGRID.  Le processus de déploiement a été exécuté avec succès et l’outil d’analyse comparative TPC-DS a été utilisé pour effectuer 99 requêtes SQL sur les différentes sources de données.  Le rapport a également exploré les cas d’utilisation des clients au sein de NetApp, démontrant la polyvalence et l’efficacité de Dremio pour répondre à diverses exigences commerciales.  De plus, un cas d’utilisation spécifique impliquant un client de vente de pièces automobiles a été examiné, mettant en évidence l’application pratique et les avantages de l’exploitation de Dremio pour l’analyse et la compréhension des données.

Dans l’ensemble, ce document constitue une ressource précieuse pour comprendre le déploiement et l’utilisation de Dremio avec les contrôleurs de stockage NetApp , en présentant ses capacités et son potentiel pour favoriser la prise de décision et l’optimisation basées sur les données dans divers secteurs.



== Où trouver des informations supplémentaires

Pour en savoir plus sur les informations décrites dans ce document, consultez les documents et/ou sites Web suivants :

* Installation du gardien de zoo
+
https://medium.com/@ahmetfurkandemir/distributed-hadoop-cluster-1-spark-with-all-dependincies-03c8ec616166[]

* Dremio
+
https://docs.dremio.com/current/get-started/cluster-deployments/deployment-models/standalone/standalone-tarball/[]

* Configuration de Dremio avec storageGRID
+
https://docs.netapp.com/us-en/storagegrid-enable/tools-apps-guides/configure-dremio-storagegrid.html#configure-dremio-data-source[]

* Cas d'utilisation de NetApp
+
https://www.dremio.com/customers/netapp/[]


