---
sidebar: sidebar 
permalink: data-analytics/tr-4623.html 
keywords:  
summary:  
---
= TR-4623 : NetApp E-Series E5700 et Splunk Enterprise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Mitch Blackburn, NetApp

[role="lead"]
TR-4623 décrit l'architecture intégrée de la conception NetApp E-Series et Splunk.  Optimisée pour l'équilibre du stockage des nœuds, la fiabilité, les performances, la capacité de stockage et la densité, cette conception utilise le modèle de nœud d'index clusterisé Splunk, avec une évolutivité plus élevée et un coût total de possession plus faible.  Le découplage du stockage du calcul offre la possibilité de mettre à l'échelle chacun séparément, ce qui permet d'économiser le coût de surprovisionnement de l'un ou de l'autre.  De plus, ce document résume les résultats des tests de performances obtenus à partir d'un outil de simulation d'événements de journal de machine Splunk.

link:https://www.netapp.com/pdf.html?item=/media/16851-tr-4623pdf.pdf["TR-4623 : NetApp E-Series E5700 et Splunk Enterprise"^]
