---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'netapp, solutions, ai, what"s new, updates, change log' 
summary: 'Journal des modifications récentes apportées aux supports des solutions d"intelligence artificielle NetApp .' 
---
= Quoi de neuf dans les solutions d'intelligence artificielle NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés en matière de solutions d’intelligence artificielle.



== 18 août 2025

Le site NetApp Solutions est désormais lelink:https://docs.netapp.com/us-en/netapp-solutions-family/index.html["Famille de solutions NetApp"^] , qui comprend les sites suivants :

* Solutions d'intelligence artificielle NetApp
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/index.html["Solutions de conteneurs NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-dataops/index.html["Solutions de gestion de données NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-databases/index.html["Solutions de base de données NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/index.html["Solutions de cloud public et hybride NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-sap/index.html["Solutions NetApp pour SAP"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/index.html["Solutions de virtualisation NetApp"^]




== 3 décembre 2025

Nouvelle solution :link:software/ai-hybrid-union.html["Déployez une formation hybride en IA avec Union.ai et NetApp FlexCache"]

Utilisez l'orchestration Union.ai avec NetApp FlexCache pour exécuter des charges de travail d'entraînement d'IA sur des GPU cloud tout en conservant les données sensibles sur site.  FlexCache ne met en cache dans le cloud que les données nécessaires pour une formation hybride efficace et sécurisée.
