---
sidebar: sidebar 
permalink: infra/ai-lenovo-edge-plan.html 
keywords: test, plan, mlperf, inference, benchmarks 
summary: Ce document suit le code MLPerf Inference v0.7, le code et les règles MLPerf Inference v1.1.  Nous avons exécuté des tests de référence conçus pour l’inférence à la périphérie, comme défini dans les tableaux présentés dans cette section. 
---
= Plan de test
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce document suit MLPerf Inference v0.7 https://github.com/mlperf/inference_results_v0.7/tree/master/closed/Lenovo["code"^] , Inférence MLPerf v1.1 https://github.com/mlcommons/inference_results_v1.1/tree/main/closed/Lenovo["code"^] , et https://github.com/mlcommons/inference_policies/blob/master/inference_rules.adoc["règles"^] .  Nous avons exécuté des tests MLPerf conçus pour l’inférence à la périphérie, comme défini dans le tableau suivant.

|===
| Zone | Tâche | Modèle | Ensemble de données | Taille QSL | Qualité | Contrainte de latence multiflux 


| Vision | Classification des images | Resnet50v1.5 | ImageNet (224x224) | 1024 | 99% du FP32 | 50 ms 


| Vision | Détection d'objets (grand) | SSD-ResNet34 | COCO (1200x1200) | 64 | 99% du FP32 | 66 ms 


| Vision | Détection d'objet (petit) | SSD-MobileNetsv1 | COCO (300x300) | 256 | 99% du FP32 | 50 ms 


| Vision | Segmentation d'images médicales | UNET 3D | BraTS 2019 (224x224x160) | 16 | 99% et 99,9% du FP32 | n / A 


| Discours | Conversion de la parole en texte | RNNT | Librispeech dev-clean | 2513 | 99% du FP32 | n / A 


| Langue | Traitement du langage | BERT | SQuAD v1.1 | 10833 | 99% du FP32 | n / A 
|===
Le tableau suivant présente les scénarios de référence Edge.

|===
| Zone | Tâche | Scénarios 


| Vision | Classification des images | Flux unique, hors ligne, multiflux 


| Vision | Détection d'objets (grand) | Flux unique, hors ligne, multiflux 


| Vision | Détection d'objet (petit) | Flux unique, hors ligne, multiflux 


| Vision | Segmentation d'images médicales | Flux unique, hors ligne 


| Discours | Conversion de la parole en texte | Flux unique, hors ligne 


| Langue | Traitement du langage | Flux unique, hors ligne 
|===
Nous avons effectué ces tests de référence en utilisant l'architecture de stockage en réseau développée dans cette validation et comparé les résultats à ceux des exécutions locales sur les serveurs périphériques précédemment soumis à MLPerf.  La comparaison vise à déterminer l’impact du stockage partagé sur les performances d’inférence.
