---
sidebar: sidebar 
permalink: infra/ai-lenovo-train-arch.html 
keywords: adjustments 
summary: 'La configuration utilisée pour la validation peut être ajustée pour s"adapter à d"autres cas d"utilisation.' 
---
= Ajustements d'architecture
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La configuration utilisée pour cette validation peut être ajustée pour s'adapter à d'autres cas d'utilisation.



== Réglages du processeur

Nous avons utilisé un processeur Skylake Intel Xeon Platinum 8360Y pour cette validation, comme recommandé par Lenovo.  Nous nous attendons à ce que le processeur Cascade Lake équivalent, un processeur Intel Xeon Gold 6330, offre des performances similaires, car cette charge de travail n'est pas liée au processeur.



== Augmentation de la capacité de stockage

En fonction de vos besoins en capacité de stockage, vous pouvez augmenter le stockage partagé (volume NFS) à la demande, à condition de disposer d'étagères de disques et de modèles de contrôleur supplémentaires.  Vous pouvez le faire à partir de l'interface de ligne de commande ou de l'interface Web NetApp du contrôleur de stockage en tant qu'utilisateur administrateur.
