---
sidebar: sidebar 
permalink: software/ai-nvaie-vmw-tech.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA AI Enterprise avec NetApp et VMware - Présentation de la technologie 
---
= Aperçu de la technologie
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section fournit un aperçu technologique de NVIDIA AI Enterprise avec NetApp et VMware.



== NVIDIA AI Enterprise

NVIDIA AI Enterprise est une suite de logiciels d'IA et d'analyse de données cloud native de bout en bout, optimisée, certifiée et prise en charge par NVIDIA pour s'exécuter sur VMware vSphere avec les systèmes certifiés NVIDIA.  Ce logiciel facilite le déploiement, la gestion et la mise à l’échelle simples et rapides des charges de travail d’IA dans l’environnement cloud hybride moderne.



== NVIDIA GPU Cloud (NGC)

NVIDIA NGC héberge un catalogue de logiciels optimisés pour GPU permettant aux praticiens de l'IA de développer leurs solutions d'IA.  Il donne également accès à divers services d'IA, notamment NVIDIA Base Command pour la formation des modèles, NVIDIA Fleet Command pour déployer et surveiller les modèles, et le registre privé NGC pour accéder et gérer en toute sécurité les logiciels d'IA propriétaires.  Les clients NVIDIA AI Enterprise peuvent également demander de l’assistance via le portail NGC.



== VMware vSphere

VMware vSphere est la plateforme de virtualisation de VMware, qui transforme les centres de données en infrastructures informatiques agrégées incluant des ressources CPU, de stockage et réseau. vSphere gère ces infrastructures comme un environnement d'exploitation unifié et fournit aux administrateurs les outils nécessaires pour gérer les centres de données qui y participent.

Les deux composants principaux de vSphere sont ESXi et vCenter Server.  ESXi est la plateforme de virtualisation sur laquelle les administrateurs créent et exécutent des machines virtuelles et des appliances virtuelles. vCenter Server est le service qui leur permet de gérer plusieurs hôtes connectés à un réseau et de regrouper les ressources des hôtes.



== NetApp ONTAP

ONTAP 9, la dernière génération de logiciel de gestion du stockage de NetApp, permet aux entreprises de moderniser leur infrastructure et de passer à un centre de données prêt pour le cloud.  En s'appuyant sur des capacités de gestion de données de pointe, ONTAP permet la gestion et la protection des données avec un seul ensemble d'outils, quel que soit l'endroit où résident ces données.  Vous pouvez également déplacer librement les données là où elles sont nécessaires : vers la périphérie, le cœur ou le cloud.  ONTAP 9 inclut de nombreuses fonctionnalités qui simplifient la gestion des données, accélèrent et protègent les données critiques et permettent des capacités d'infrastructure de nouvelle génération dans les architectures de cloud hybride.



=== Simplifier la gestion des données

La gestion des données est essentielle pour les opérations informatiques de l’entreprise et les scientifiques des données afin que les ressources appropriées soient utilisées pour les applications d’IA et la formation des ensembles de données d’IA/ML.  Les informations supplémentaires suivantes sur les technologies NetApp ne sont pas couvertes par cette validation, mais peuvent être pertinentes en fonction de votre déploiement.

Le logiciel de gestion des données ONTAP comprend les fonctionnalités suivantes pour rationaliser et simplifier les opérations et réduire votre coût total d'exploitation :

* Compactage des données en ligne et déduplication étendue.  La compaction des données réduit l’espace gaspillé à l’intérieur des blocs de stockage et la déduplication augmente considérablement la capacité effective.  Cela s’applique aux données stockées localement et aux données hiérarchisées vers le cloud.
* Qualité de service minimale, maximale et adaptative (AQoS).  Les contrôles granulaires de qualité de service (QoS) aident à maintenir les niveaux de performances des applications critiques dans les environnements hautement partagés.
* FabricPool NetApp .  Fournit une hiérarchisation automatique des données froides vers des options de stockage cloud publiques et privées, notamment Amazon Web Services (AWS), Azure et la solution de stockage NetApp StorageGRID .  Pour plus d'informations sur FabricPool, voir https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598 : Bonnes pratiques FabricPool"^] .




=== Accélérer et protéger les données

ONTAP offre des niveaux supérieurs de performance et de protection des données et étend ces capacités des manières suivantes :

* Performances et latence réduite.  ONTAP offre le débit le plus élevé possible avec la latence la plus faible possible.
* Protection des données.  ONTAP fournit des fonctionnalités de protection des données intégrées avec une gestion commune sur toutes les plates-formes.
* Chiffrement de volume NetApp (NVE).  ONTAP offre un cryptage natif au niveau du volume avec prise en charge de la gestion des clés intégrée et externe.
* Authentification multi-locataire et multifactorielle.  ONTAP permet le partage des ressources d'infrastructure avec les plus hauts niveaux de sécurité.




=== Une infrastructure à l'épreuve du temps

ONTAP permet de répondre aux besoins commerciaux exigeants et en constante évolution grâce aux fonctionnalités suivantes :

* Mise à l’échelle transparente et opérations non perturbatrices.  ONTAP prend en charge l'ajout non perturbateur de capacité aux contrôleurs existants et aux clusters évolutifs.  Les clients peuvent passer aux dernières technologies, telles que NVMe et FC 32 Go, sans migrations de données ni pannes coûteuses.
* Connexion au Cloud.  ONTAP est le logiciel de gestion de stockage le plus connecté au cloud, avec des options de stockage défini par logiciel (ONTAP Select) et des instances cloud natives (Google Cloud NetApp Volumes) dans tous les clouds publics.
* Intégration avec les applications émergentes.  ONTAP propose des services de données de niveau entreprise pour les plates-formes et applications de nouvelle génération, telles que les véhicules autonomes, les villes intelligentes et l'industrie 4.0, en utilisant la même infrastructure qui prend en charge les applications d'entreprise existantes.




== Boîte à outils NetApp DataOps

NetApp DataOps Toolkit est un outil basé sur Python qui simplifie la gestion des espaces de travail de développement/formation et des serveurs d'inférence soutenus par un stockage NetApp hautes performances et évolutif.  Les principales fonctionnalités comprennent :

* Provisionnez rapidement de nouveaux espaces de travail JupyterLab haute capacité soutenus par un stockage NetApp hautes performances et évolutif.
* Provisionnez rapidement de nouvelles instances de NVIDIA Triton Inference Server soutenues par un stockage NetApp de classe entreprise.
* Clonez presque instantanément des espaces de travail JupyterLab de grande capacité afin de permettre l'expérimentation ou l'itération rapide.
* Enregistrez presque instantanément des instantanés d'espaces de travail JupyterLab haute capacité pour la sauvegarde et/ou la traçabilité/l'établissement de référence.
* Provisionnez, clonez et capturez des instantanés de volumes de données haute capacité et hautes performances de manière quasi instantanée.

