---
sidebar: sidebar 
permalink: software/ai-nvaie-vmw-setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA AI Enterprise avec NetApp et VMware - Configuration initiale 
---
= Configuration initiale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section décrit les tâches de configuration initiales qui doivent être effectuées pour utiliser NVIDIA AI Enterprise avec NetApp et VMware.



== Prérequis

Avant d’effectuer les étapes décrites dans cette section, nous supposons que vous avez déjà déployé VMware vSphere et NetApp ONTAP.  Se référer à lalink:https://docs.nvidia.com/ai-enterprise/latest/product-support-matrix/index.html["Matrice de support des produits NVIDIA AI Enterprise"^] pour plus de détails sur les versions de vSphere prises en charge.  Se référer à lalink:https://docs.netapp.com/us-en/netapp-solutions/vmware/index.html["Documentation des solutions NetApp et VMware"^] pour plus de détails sur le déploiement de VMware vSphere avec NetApp ONTAP.



== Installer le logiciel hôte NVIDIA AI Enterprise

Pour installer le logiciel hôte NVIDIA AI Entrprise, suivez les instructions décrites dans les sections 1 à 4 dulink:https://docs.nvidia.com/ai-enterprise/latest/quick-start-guide/index.html["Guide de démarrage rapide de NVIDIA AI Enterprise"] .
