---
sidebar: sidebar 
permalink: software/dataops-toolkit.html 
keywords:  
summary:  
---
= Boîte à outils NetApp DataOps
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp DataOps Toolkit est un outil basé sur Python qui simplifie la gestion des espaces de travail de développement/formation et des serveurs d'inférence soutenus par un stockage NetApp hautes performances et évolutif.  Les principales fonctionnalités comprennent :

* Provisionnez rapidement de nouveaux espaces de travail JupyterLab haute capacité soutenus par un stockage NetApp hautes performances et évolutif.
* Provisionnez rapidement de nouvelles instances de NVIDIA Triton Inference Server soutenues par un stockage NetApp de classe entreprise.
* Clonez presque instantanément des espaces de travail JupyterLab de grande capacité afin de permettre l'expérimentation ou l'itération rapide.
* Enregistrez presque instantanément des instantanés d'espaces de travail JupyterLab haute capacité pour la sauvegarde et/ou la traçabilité/l'établissement de référence.
* Provisionnez, clonez et capturez des instantanés quasi instantanément de volumes de données haute capacité et hautes performances.


link:https://github.com/NetApp/netapp-dataops-toolkit["Boîte à outils NetApp DataOps"^]
